### PR TITLE
Added documentation for Panasonic sponsored features

### PR DESCRIPTION
**Pull request by JamesCullum**
Added documentation for

- Engagement Planner
- Tool Run

Changed documentation for

- Port Scan

Added images for

- New documentation
- Panasonic sponsorship

### CODE REVIEW

**Comment by JamesCullum** [comment]
Related to this PR in DefectDojo: https://github.com/DefectDojo/django-DefectDojo/pull/981

**Comment by ppiotr3k** [comment]
@JamesCullum, could you please merge JamesCullum/Documentation#1 before this PR is merged? I'm Trying to avoid introducing Sphinx warnings. Thanks! :smiley:

**Comment by JamesCullum** [comment]
@ppiotr3k Thank you very much, done! 👍 

Looks like Travis errors are still there, though :/

**Comment by ppiotr3k** [comment]
> @ppiotr3k Thank you very much, done! +1
> 
> Looks like Travis errors are still there, though :/

Yes, it is due to pending merge of #28 as I tried to explain in my JamesCullum#1 comment. After maintainers merge #28, the check will pass (you can see it in #28 conversation).

**Comment by JamesCullum** [comment]
Feature abandoned by DD team

**Pull request closed without merging**
