### PR TITLE
New param to enable Gitlab projects auto-import

### PR DESCRIPTION
**Pull request by christophe226**
Fix django-DefectDojo Issue 1984

### CODE REVIEW

**Comment by christophe226** [comment]
Related to django-DefectDojo PR 2211

**Comment by mtesauro** [comment]
Links to the mentioned issue & PR
[DefectDojo Issue #1984](https://github.com/DefectDojo/django-DefectDojo/issues/1984)
[DefectDojo PR 2211](https://github.com/DefectDojo/django-DefectDojo/pull/2211)

**Comment by valentijnscholten** [comment]
Not sure how we want to handle these version dependant documentation updates. This feature is not in dev yet, let alone in a release.

**Comment by madchap** [comment]
True.. i was a little too hasty here.

I guess this is another point to having doc in-repo.

**Comment by madchap** [comment]
Reverted.

**Pull request merged**
