### PR TITLE
 Add linting capabilities to repository

### PR DESCRIPTION
**Pull request by ppiotr3k**
Add `validate` target in Makefile to check for warnings and missing references.
Add Travis-CI configuration file to break on warnings and missing references.

Signed-off-by: Piotr PAWLICKI <piotrek@seovya.net>

### CODE REVIEW

**Comment by aaronweaver** [comment]
Is the job failing b/c of linting? It wasn't clear in the error above?

**Comment by devGregA** [comment]
https://travis-ci.com/DefectDojo/Documentation/builds/105518148

**Comment by ppiotr3k** [comment]
> Is the job failing b/c of linting? It wasn't clear in the error above?

Hi @aaronweaver and @devGregA , thanks for having a look!

The result of the Travis-CI job (ran on the proposed `.travis.yml` config) demonstrates indeed the current documentation has warnings and errors, which should break the build. Most of them are related to missing blank lines, tag usage errors and not referenced existing content (ex: API v2 page).

This PR is therefore to add a `.travis.yml`, which at the moment only features a check for linting, using a Sphinx dummy builder. The same check is added to the `Makefile`, so contributors can run it locally before pushing code, via `make validate`.

#25 is an attempt on correcting all warning and errors issues - except one: unknown reference to a `reports.sh` file, for which I asked on Slack. No luck so far.

After merging this PR, #25 , and fixing the missing `reports.sh` issue, the documentation will finally build all green! :blush: It will then be way easier to control that new contributions don't introduce neither errors nor warnings.

**Comment by ppiotr3k** [comment]
> 
> After merging this PR, #25 , and fixing the missing `reports.sh` issue, the documentation will finally build all green! :blush:  It will then be way easier to control that new contributions don't introduce neither errors nor warnings.

I forgot to mention, in the current state of the repo (before #25), some warnings have more important consequences on the rendered documentation than others.

Especially when the content is:
- **not** rendered (because: missing blank line, thus interpreted as parameters for a tag)
- excluded/included in a list of commands it does/doesn't belong to (because: indentation issues)
- not referenced, so not available unless using search (because: page not referenced by any other page)

Thus also IMHO the importance of detecting such warnings and handling them.

**Comment by aaronweaver** [comment]
Merging, no idea about reports.sh can be removed.

**Pull request merged**
