### PR TITLE
Start doc page for variables introduced in settings

### PR DESCRIPTION
**Pull request by madchap**

### CODE REVIEW

**Review by valentijnscholten — APPROVED** [review]
Maybe add WIP so readers now it's WIP?

**Comment by madchap** [comment]
I was about to do it, and then figured it'd be obvious. I am afraid WIP would always be kind of the case? :trollface:

**Comment by valentijnscholten** [comment]
True. Maybe put all the cars in there, but without docs? To give an idea to people what can be configured?

**Comment by madchap** [comment]
Added the vars starting with `DD_`. To be completed over time.

**Comment by madchap** [comment]
Not sure what's happening here. Building locally with 

```
$ sphinx-build -nWT -b dummy . _build/html
Running Sphinx v3.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [dummy]: targets for 14 source files that are out of date
updating environment: [new config] 14 added, 0 changed, 0 removed
reading sources... [100%] workflows                                                                                                          
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] workflows                                                                                                           
build succeeded.

The dummy builder generates no files.

```

Seems OK. I guess we could also up that package version in Travis.

**Pull request merged**
